#!/bin/zsh

COMPARAÇÕES="$HOME/Comparações/Yaru++ Development/Icons/" 
ÍCONES="$HOME/Imagens/Ícones/"
YARUO="$HOME/GitHub/yaru-plus/"
YARUB="$HOME/GitHub/yaru-plus-beta/"
YARUG="$HOME/GitHub/yaru-plus-gusbemacbe/"

# External HD

HDYARUO="/run/media/gusbemacbe/Gits/GitHub/Andrea/yaru-plus/"
HDYARUB="/run/media/gusbemacbe/Gits/GitHub/Andrea/yaru-plus-beta/"
HDYARUG="/run/media/gusbemacbe/Gits/GitHub/Andrea/yaru-plus-gusbemacbe/"

# cd $YARUB

cp $HDYARUB/Yaru++/mimetypes/16/1E64_notepad.0.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/4137_winhlp32.0.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/A35F_hh.0.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/amazon-mp3-store-source.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-7z.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-amazon.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-apk.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-bittorrent.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-cd.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-certificate.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-colors.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-desktop.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-ebook.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-eps.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-epub+zip.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-epub.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-executable.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-firmware.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-flash.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-flatpak.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-gcstar.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-geo+json.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-glabels.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-gzip.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-help.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-illustrator.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-img.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-ipynb.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-java.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-json.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-karbon.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-keepassxc.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-krita.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-lmms.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-maps.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-msaccess.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-msexcel.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-msi.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-mspowerpoint.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-mswinurl.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-msword.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-musescore.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-note.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-octet-stream.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-pdf.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-perl.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-pgp-keys.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-pgp.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-photoshop.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-php.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-rar.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-raw.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-rss+xml.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-rss.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-rss_xml.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-ruby.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-shellscript.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-snap.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-sql.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-squashfs.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-theme.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-trash.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-vnd.debian.binary-package.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-vnd.flatpak.ref.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-vnd.google-earth.kml+xml.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-archive.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-bittorrent.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-desktop.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-firmware.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-flash-video.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-gameboy-rom.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-gcstar.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-java.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-json.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-keepassxc.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-mobipocket-ebook.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-msi.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-partial-download.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-php.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-raw-disk-image.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-rss+xml.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-rss.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-rss_xml.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-ruby.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-sharedlib.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-shellscript.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-theme.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-trash.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-yaml.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-x-zip.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-xmind.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/application-yaml.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/audio-x-generic.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/audio-x-scpls.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/audio.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/debian.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/empty.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/exec.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/extension.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/font-x-generic.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/gnome-mime-application-x-audacity-project.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/gnome-mime-application-x-bittorrent.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/gnome-mime-application-x-shellscript.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/gnome-mime-text-x-sh.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/image-cursor.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/image-svg.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/image-xcf.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/image.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/inode-symlink.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/libreoffice-database.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/libreoffice-drawing.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/libreoffice-formula.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/libreoffice-oasis-master-document.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/libreoffice-oasis-spreadsheet-template.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/libreoffice-presentation.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/libreoffice-text.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/libreoffice-web.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/message-rfc822.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/message.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/model-x.stl-binary.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/model.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/office-presentation.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/office-spreadsheet.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/package-gdebi.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/package.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/shellscript.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-arduino.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-authors.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-bibtex.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-c++.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-c.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-changelog.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-chdr.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-cmake.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-cobol.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-copying.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-credits.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-csharp.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-css.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-dockerfile.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-fortran.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-gettext-translation.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-go.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-haskell.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-html.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-install.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-java.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-javascript.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-kotlin.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-less.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-lilypond.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-log.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-lua.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-markdown.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-maven.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-meson.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-nim.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-php.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-python.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-qml.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-r.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-readme.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-richtext.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-rust.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-scala.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-script.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-scss.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-ssa.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-tex.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-typescript.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-vala.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-bibtex.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-c++.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-c.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-changelog.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-chdr.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-cmake.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-cobol.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-copying.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-credits.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-csharp.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-fortran.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-gettext-translation-template.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-gettext-translation.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-go.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-haskell.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-install.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-java-source.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-java.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-javascript.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-kotlin.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-lua.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-markdowm.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-nim.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-php.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-python.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-r.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-readme.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-richtext.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-rust.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-script.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-scss.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-ssa.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-tex.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-theme.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-typescript.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-vala.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-x-xml.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text-xml.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/text.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/unknown.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/video.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/vnd.ms-publisher.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/x-office-document.svg $ÍCONES/mimetypes/16/
cp $HDYARUB/Yaru++/mimetypes/16/x-package-repository.svg $ÍCONES/mimetypes/16/

# Yaru++/mimetypes/24
# Yaru++/mimetypes/32

cp $HDYARUB/Yaru++/mimetypes/48/1E64_notepad.0.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/2402_msiexec.0.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/4137_winhlp32.0.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/A35F_hh.0.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/amazon-mp3-store-source.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-7z.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-amazon.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-bittorrent.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-cd.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-colors.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-desktop.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-ebook.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-epub.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-executable.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-firmware.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-flash.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-flatpak.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-gcstar.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-geo+json.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-glabels.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-gzip.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-help.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-img.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-ipynb.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-karbon.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-keepassxc.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-krita.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-lmms.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-maps.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-msi.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-mswinurl.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-musescore.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-note.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-octet-stream.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-perl.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-pgp-encrypted.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-pgp-keys.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-pgp-signature.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-php.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-rar.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-raw.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-rss+xml.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-rss.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-ruby.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-shellscript.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-snap.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-sql.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-squashfs.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-theme.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-trash.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-vnd.flatpak.ref.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-vnd.google-earth.kml+xml.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-vnd.iccprofile.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-desktop.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-flash-video.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-gcstar.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-java-archive.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-json.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-keepassxc.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-mobipocket-ebook.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-ms-dos-executable.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-msi.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-perl.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-php.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-python-bytecode.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-raw-disk-image.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-rss+xml.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-rss.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-rss_xml.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-ruby.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-sharedlib.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-shellscript.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-theme.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-virtualbox-hdd.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-virtualbox-ova.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-virtualbox-ovf.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-virtualbox-vbox-extpack.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-virtualbox-vbox.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-virtualbox-vdi.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-virtualbox-vhd.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-virtualbox-vmdk.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-x-zip.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/application-yaml.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/audio-mpeg.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/audio-x-adpcm.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/audio-x-midi.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/audio-x-ms-wma.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/audio-x-vorbis+ogg.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/audio-x-wav.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/audio.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/binary.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/debian.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/exec.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/gnome-mime-application-x-shellscript.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/gnome-mime-text-x-sh.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/image-cursor.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/image-svg.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/image-xcf.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/message-rfc822.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/message.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/model-x.stl-binary.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/model.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/shellscript.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-arduino.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-bibtex.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-c++.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-c.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-changelog.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-chdr.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-cmake.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-cobol.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-copying.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-credits.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-csharp.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-dockerfile.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-fortran.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-gettext-translation.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-go.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-haskell.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-install.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-java.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-javascript.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-kotlin.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-lilypond.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-log.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-lua.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-maven.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-meson.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-nim.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-php.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-python.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-qml.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-r.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-readme.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-scala.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-script.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-scss.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-ssa.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-tex.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-typescript.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-vala.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-c++.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-c.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-changelog.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-chdr.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-cmake.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-cobol.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-copying.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-credits.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-csharp.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-fortran.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-gettext-translation-template.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-gettext-translation.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-go.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-haskell.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-install.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-java-source.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-java.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-javascript.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-kotlin.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-lua.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-markdowm.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-meson.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-nim.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-php.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-python.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-r.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-readme.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-richtext.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-rust.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-script.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-scss.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-ssa.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-systemd-unit.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-tex.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-theme.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-typescript.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-vala.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/text-x-xml.svg $ÍCONES/mimetypes/48/
cp $HDYARUB/Yaru++/mimetypes/48/video.svg $ÍCONES/mimetypes/48/

cp $HDYARUB/Yaru++/mimetypes/scalable/1E64_notepad.0.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/2402_msiexec.0.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/4137_winhlp32.0.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/A35F_hh.0.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/amazon-mp3-store-source.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-7z.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-amazon.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-bittorrent.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-cd.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-colors.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-desktop.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-ebook.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-epub+zip.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-epub.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-executable.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-firmware.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-flash.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-flatpak-ref.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-flatpak.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-gcstar.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-geo+json.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-glabels.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-gzip.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-help.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-img.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-ipynb.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-karbon.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-keepassxc.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-krita.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-lmms.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-maps.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-msi.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-mswinurl.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-musescore.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-note.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-perl.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-pgp-encrypted.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-pgp-keys.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-pgp-signature.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-php.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-rar.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-raw.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-rss+xml.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-rss.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-ruby.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-shellscript.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-snap.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-squashfs.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-theme.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-trash.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-vnd.flatpak.ref.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-vnd.flatpak.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-vnd.google-earth.kml+xml.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-vnd.iccprofile.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-bittorrent.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-desktop.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-flash-video.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-gcstar.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-json.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-keepassxc.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-mobipocket-ebook.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-ms-dos-executable.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-msi.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-php.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-python-bytecode.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-rss+xml.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-rss.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-rss_xml.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-ruby.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-sharedlib.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-shellscript.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-theme.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-virtualbox-hdd.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-virtualbox-ova.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-virtualbox-ovf.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-virtualbox-vbox-extpack.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-virtualbox-vbox.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-virtualbox-vdi.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-virtualbox-vhd.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-virtualbox-vmdk.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-x-yaml.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/application-yaml.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/audio-mpeg.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/audio-x-adpcm.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/audio.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/binary.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/debian.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/exec.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/gnome-mime-application-x-shellscript.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/gnome-mime-text-x-sh.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/image-cursor.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/image-svg.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/image-xcf.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/message-rfc822.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/message.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/model-x.stl-binary.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/package-gdebi.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/shellscript.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-arduino.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-bibtex.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-c++.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-c.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-changelog.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-chdr.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-cmake.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-cobol.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-copying.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-credits.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-csharp.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-dockerfile.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-fortran.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-gettext-translation.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-go.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-haskell.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-install.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-java.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-javascript.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-kotlin.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-lilypond.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-log.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-lua.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-maven.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-meson.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-nim.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-php.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-python.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-qml.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-r.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-readme.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-richtext.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-scala.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-script.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-scss.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-ssa.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-tex.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-typescript.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-vala.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-c++.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-c.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-changelog.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-chdr.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-cmake.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-cobol.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-copying.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-credits.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-csharp.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-fortran.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-gettext-translation-template.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-gettext-translation.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-go.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-haskell.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-install.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-java-source.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-java.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-javascript.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-kotlin.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-lua.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-markdowm.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-meson.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-nim.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-php.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-python.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-r.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-readme.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-richtext.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-rust.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-script.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-scss.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-ssa.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-systemd-unit.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-tex.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-theme.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-typescript.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-vala.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/text-x-xml.svg $ÍCONES/mimetypes/scalable/
cp $HDYARUB/Yaru++/mimetypes/scalable/video.svg $ÍCONES/mimetypes/scalable/

cp $HDYARUB/Yaru++/mimetypes/symbolic/application-executable-symbolic.svg $ÍCONES/mimetypes/symbolic/
cp $HDYARUB/Yaru++/mimetypes/symbolic/application-x-rss_xml-symbolic.svg $ÍCONES/mimetypes/symbolic/
cp $HDYARUB/Yaru++/mimetypes/symbolic/image-x-generic-symbolic.svg $ÍCONES/mimetypes/symbolic/
cp $HDYARUB/Yaru++/mimetypes/symbolic/text-x-generic-symbolic.svg $ÍCONES/mimetypes/symbolic/
cp $HDYARUB/Yaru++/mimetypes/symbolic/x-office-calendar-symbolic.svg $ÍCONES/mimetypes/symbolic/
cp $HDYARUB/Yaru++/mimetypes/symbolic/x-office-document-symbolic.svg $ÍCONES/mimetypes/symbolic/