#!/bin/sh

YARU="$HOME/Comparisons/Yaru++ Development/Icons/places/scalable"

ln -sfnr $YARU/folder-yaru-android.png     $YARU/folder-android.png
ln -sfnr $YARU/folder-yaru-app.png         $YARU/folder-app.png
ln -sfnr $YARU/folder-yaru-aur.png         $YARU/folder-aur.png
ln -sfnr $YARU/folder-yaru-bitbucket.png   $YARU/folder-bitbucket.png
ln -sfnr $YARU/folder-yaru-config.png      $YARU/folder-config.png
ln -sfnr $YARU/folder-yaru-design.png      $YARU/folder-design.png
ln -sfnr $YARU/folder-yaru-dictionary.png  $YARU/folder-dictionary.png
ln -sfnr $YARU/folder-yaru-font.png        $YARU/folder-font.png
ln -sfnr $YARU/folder-yaru-freedesktop.png $YARU/folder-freedesktop.pn
ln -sfnr $YARU/folder-yaru-go.png          $YARU/folder-go.png
ln -sfnr $YARU/folder-yaru-heroku.png      $YARU/folder-heroku.png
ln -sfnr $YARU/folder-yaru-intellij.png    $YARU/folder-intellij.png
ln -sfnr $YARU/folder-yaru-invoice.png     $YARU/folder-invoice.png
ln -sfnr $YARU/folder-yaru-iso.png         $YARU/folder-iso.png
ln -sfnr $YARU/folder-yaru-javascript.png  $YARU/folder-javascript.png
ln -sfnr $YARU/folder-yaru-kotlin.png      $YARU/folder-kotlin.png
ln -sfnr $YARU/folder-yaru-library.png     $YARU/folder-library.png
ln -sfnr $YARU/folder-yaru-log.png         $YARU/folder-log.png
ln -sfnr $YARU/folder-yaru-maths.png       $YARU/folder-maths.png
ln -sfnr $YARU/folder-yaru-nodejs.png      $YARU/folder-nodejs.png
ln -sfnr $YARU/folder-yaru-onedrive.png    $YARU/folder-onedrive.png
ln -sfnr $YARU/folder-yaru-php.png         $YARU/folder-php.png
ln -sfnr $YARU/folder-yaru-python.png      $YARU/folder-python.png
ln -sfnr $YARU/folder-yaru-template.png    $YARU/folder-template.png
ln -sfnr $YARU/folder-yaru-virtualbox.png  $YARU/folder-virtualbox.png
ln -sfnr $YARU/folder-yaru-vscode.png      $YARU/folder-vscode.png
ln -sfnr $YARU/folder-yaru-android.svg     $YARU/folder-android.svg
ln -sfnr $YARU/folder-yaru-app.svg         $YARU/folder-app.svg
ln -sfnr $YARU/folder-yaru-aur.svg         $YARU/folder-aur.svg
ln -sfnr $YARU/folder-yaru-bitbucket.svg   $YARU/folder-bitbucket.svg
ln -sfnr $YARU/folder-yaru-config.svg      $YARU/folder-config.svg
ln -sfnr $YARU/folder-yaru-design.svg      $YARU/folder-design.svg
ln -sfnr $YARU/folder-yaru-dictionary.svg  $YARU/folder-dictionary.svg
ln -sfnr $YARU/folder-yaru-font.svg        $YARU/folder-font.svg
ln -sfnr $YARU/folder-yaru-freedesktop.svg $YARU/folder-freedesktop.sv
ln -sfnr $YARU/folder-yaru-go.svg          $YARU/folder-go.svg
ln -sfnr $YARU/folder-yaru-heroku.svg      $YARU/folder-heroku.svg
ln -sfnr $YARU/folder-yaru-intellij.svg    $YARU/folder-intellij.svg
ln -sfnr $YARU/folder-yaru-invoice.svg     $YARU/folder-invoice.svg
ln -sfnr $YARU/folder-yaru-iso.svg         $YARU/folder-iso.svg
ln -sfnr $YARU/folder-yaru-javascript.svg  $YARU/folder-javascript.svg
ln -sfnr $YARU/folder-yaru-kotlin.svg      $YARU/folder-kotlin.svg
ln -sfnr $YARU/folder-yaru-library.svg     $YARU/folder-library.svg
ln -sfnr $YARU/folder-yaru-log.svg         $YARU/folder-log.svg
ln -sfnr $YARU/folder-yaru-maths.svg       $YARU/folder-maths.svg
ln -sfnr $YARU/folder-yaru-nodejs.svg      $YARU/folder-nodejs.svg
ln -sfnr $YARU/folder-yaru-onedrive.svg    $YARU/folder-onedrive.svg
ln -sfnr $YARU/folder-yaru-php.svg         $YARU/folder-php.svg
ln -sfnr $YARU/folder-yaru-python.svg      $YARU/folder-python.svg
ln -sfnr $YARU/folder-yaru-template.svg    $YARU/folder-template.svg
ln -sfnr $YARU/folder-yaru-virtualbox.svg  $YARU/folder-virtualbox.svg
ln -sfnr $YARU/folder-yaru-vscode.svg      $YARU/folder-vscode.svg
