name: Travis

on:
  pull_request:
  push:
    branches:
      - gusbemacbe

jobs:
  run_tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master
    - name: Install neofetch and xmlstarlet
      run: sudo apt-get install neofetch xmlstarlet yaru-theme-icon
    - name: Analysing and testing
      run: neofetch && ls /usr/share/icons && make -k test-all
